### ISSUE TITLE
Facebook Calendar is missing

### ISSUE THREAD

**Issue by ghost** [insanum/gcalcli#281] opened 2017-01-26 23:19 UTC
Hello today realized that my Facebook Calendar which already linked to Google calendar is not seenable in `gcalcli calw` even if it exist in `gcalcli list`

**Comment by tresni** [comment] 2017-02-21 00:38
If you can give steps to reproduce it might be helpful.  I have no idea how to link my facebook calendar to google calendar and didn't find instructions quickly googling.   You could try a `gcalcli --refresh calw` to see if that helps.  Also make sure your `.gcalclirc` isn't limiting the calendars with `--defaultCalendar` options.

**Comment by jcrowgey** [comment] 2018-07-11 03:07
Closing because we don't have repro steps.  @ghost if this is still an issue please follow up here.

**Closed by jcrowgey** 2018-07-11 03:07 UTC
