### ISSUE TITLE
gcalcli 4.0.0 GA release?

### ISSUE THREAD

**Issue by rgdoliveira** [insanum/gcalcli#360] opened 2018-07-26 16:34 UTC
Hello,
I didn't find any Mailing List or irc for this project so I'm going to ask it here.

If I understood correctly, releases "4.0.0a4", "4.0.0a3" and so on are Alpha versions. Alpine Linux current package version 3.4.0 and I would like to upgrade to the new version but for that I needed to know if there is any plan/date to release the GA version?

**Comment by jcrowgey** [comment] 2018-07-28 14:50
Hi there,

I'm relatively new on this project so I'm also unclear as to what the plan is for the next release.

I've been very focused on code quality and testing.  Perhaps one of the original authors can update this thread with respect to release plans.

**Comment by tresni** [comment] 2018-07-28 20:21
My plan for 4.0.0 was to get rid of the gflags dependency and try to make everything else work as expected using the latest google libraries.

**Comment by rgdoliveira** [comment] 2018-08-01 11:36
@tresni Thanks for the answer. Is there any ETA for the 4.0.0 GA?

**Comment by jcrowgey** [comment] 2018-08-04 17:56
Not sure what GA stands for.  

I'll try to make an inventory of what we need to do specifically to update the google dependencies.  We have the gflags removed in master, but in my opinion, it needs more testing before we should release it.  I think it's hard to give ETAs on this type of project because the work is done by volunteers in their spare time.

At the very least we should probably push another alpha release sometime soon.

**Comment by insanum** [comment] 2018-08-06 16:50
GA mean General Availability. Marketing speak for a "release".  :-)

**Comment by jcrowgey** [comment] 2018-09-07 02:42
I'm happy to adopt @tresni's answer.  We've done part 1, removed the gflags and moved to argparse.  The part 2 is indicated in #353.  I know we also have some milestones set up with some tickets attached to them.  I'll take a look at the milestones and try to get things organized around 4.0.0 (we should fix the regression/bug tickets as well, i guess).  After I update the milestone, I'll close this issue.

**Closed** 2018-09-07 02:42 UTC

**Comment by ainola** [comment] 2018-11-16 14:51
I understand the desire to fix up oauthclient stuff, but seeing as it's now deprecated it might be worth tagging a new release - The last release was almost three years ago! :)
