### ISSUE TITLE
App Blocked and now gcalcli gives invalid_clientUnauthroized

### ISSUE THREAD

**Issue by coraxwolf** [insanum/gcalcli#624] opened 2022-01-06 17:12 UTC
I just installed this and tried it on Ubuntu.  I've tried with the install from apt-get and again with installing with pip
I was getting the App Blocked but followed the steps at https://github.com/aristosv/google_auth and now I can get the page to come up and the page says "The authentication flow has completed.", but the gcalcli exits with the error Authentication has failed: invalid_clientUnauthorized

I tried to use logging_level=DEBUG but that didn't generate any further errors.

**Comment by rsrchboy** [comment] 2022-01-18 20:03
Same here, but on archlinux, and the version in the AUR package repo.

![image](https://user-images.githubusercontent.com/59620/150010014-09c41b83-cbb1-4e83-9c66-fb097607249d.png)

**Comment by rsrchboy** [comment] 2022-01-18 20:04
Ah, this is pretty much a dupe of #580 :\

**Comment by dbarnett** [comment] 2024-08-22 23:54
Closing as dupe. Thanks for reporting!

**Closed by dbarnett** 2024-08-22 23:54 UTC
