### ISSUE TITLE
This app tried to access sensitive info in your Google Account.

### ISSUE THREAD

**Issue by MuhammadSawalhy** [insanum/gcalcli#598] opened 2021-05-08 19:07 UTC
I installed `gcalcli` using `sudo apt-get install gcalcli`. Then I run this command:

```bash
> gcalcli  list
```

A link opened in my default browser to OAuth into my account, by here is what I got:

![image](https://user-images.githubusercontent.com/42011920/117550483-f59c7880-b040-11eb-90d2-84aa50441603.png)

**Comment by DavidTre07** [comment] 2021-05-19 11:28
Duplicate of https://github.com/insanum/gcalcli/issues/580

**Comment by llvllch** [comment] 2021-08-02 21:27
I got this message when I opened the link in Firefox, switched to Chrome, it worked fine. As a general rule, for all things Google, try Chrome.

**Comment by ki11roy** [comment] 2021-08-29 18:58
Worked like a charm in Firefox with the instructions from @aristosv

**Comment by dardo82** [comment] 2022-12-20 11:46
Worked flawlessly in Google Chrome with the instructions from @aristosv! ;-)

**Comment by michaelmhoffman** [comment] 2022-12-21 16:43
I think the instructions now in `README.md` have substantively the same instructions. If there is anything that needs to be changed please open an issue.

**Closed by michaelmhoffman** 2022-12-21 16:43 UTC
