### ISSUE TITLE
can we delete or unsubscribe calendars?

### ISSUE THREAD

**Issue by kurokirasama** [insanum/gcalcli#383] opened 2018-10-01 17:44 UTC
It would be nice to have that feature!

**Comment by jcrowgey** [comment] 2018-10-09 03:34
Can't you manage this in your google settings?

Or, use the --calendars=[list] option?

**Comment by dbarnett** [comment] 2024-09-14 04:41
I think this and #597 are dupes and it's fixed now in the latest repo version via config.toml `calendars.ignore-calendars`.

Also:
> Can't you manage this in your google settings?

There is a visibility setting in Google Calendar, but I'm not sure if that's working as intended in gcalcli (#478). I think it's at least a valid feature request to exclude your hidden calendars by default if that's not already how it's working.

**Closed by dbarnett** 2024-09-14 04:41 UTC
