### ISSUE TITLE
event date wrong

### ISSUE THREAD

**Issue by kaliduss** [insanum/gcalcli#374] opened 2018-09-01 12:22 UTC
hi! i`ve tried so many variations of date an hour, and i cant seem to find the correct one. i already gave up setting "add" as i dont know how to do it, but with quick if i write for example:
gcalcli --calendar 'home' quick '2pm 09/01  text here' 
adds the event at 09/02
gcalcli --calendar 'home' quick '3pm 09/01  text here'
and this one at 09/01.
I dont know whats the problem, i've tried reviewing the code but i cant find the key function that controls date so i can enter the correct format.

**Comment by jcrowgey** [comment] 2018-09-04 03:52
I'm using the latest gcalcli and I don't seem to be able to reproduce (or I'm not following the issue correctly).

```
$ gcalcli quick '3pm 09/01 text here'
$ gcalcli search text

2019-09-01   3:00pm  text here
$
```

So, it seems like this was added for 3PM on 09/01.  What am I missing?  Are you using the latest version from master on this repo?  If not, what version are you using?

**Comment by kaliduss** [comment] 2018-09-04 19:01
also, i cant edit or delete...i get a raw_input not defined error.also, cant install from source in git, only from deb package.

**Comment by kaliduss** [comment] 2018-09-04 19:03
if i find the correct function that handles the date parsing i can know what to write so it does work, but i cant...

**Comment by jcrowgey** [comment] 2018-09-05 03:53
Thanks for the further info.

The "raw_input" not defined most likely (I'm guessing because I still don't have the full information about your setup) that you're running python3.  But the earlier versions of gcalcli were intended to be run on python2.  Perhaps simply switching to python2 will help a lot of your issues.

As to using a later version, here's one way to try it out without messing up your debian based distro: install into a virtualenvironment.

1. git clone this repo and cd 
2. create a vitualenvironment
```shell
$ virtualenv venv
```
3. source the activate script
```shell
$ source venv
```
4. install gcalcli
```shell
(venv) $ pip install .
```
5. run gcalcli as usual, test these issues you're having.  If they're still issues with the current alpha, we want to fix them asap

Thanks!

**Comment by jcrowgey** [comment] 2018-09-13 04:04
Closing for lack of repro.

**Closed by jcrowgey** 2018-09-13 04:04 UTC
