### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by Augustus175** [insanum/gcalcli#310] opened 2017-09-02 13:50 UTC
my python version is 2.7
when I run gcalcli agenda it Reported the mistake .
please help me ,thanks !

**Comment by jcrowgey** [comment] 2018-06-24 15:36
We're currently working on a bit of an overhaul in master.   Can you confirm that you still have the issue?

**Comment by jcrowgey** [comment] 2018-08-25 16:49
Since we don't have a repro case and the information we do have suggests a transient network issue, I'm closing this.  Please reopen if this is reproducible.

**Closed by jcrowgey** 2018-08-25 16:49 UTC
