### ISSUE TITLE
Gcalcli "Specify calendar from above" even the calendar was selected from command line.

### ISSUE THREAD

**Issue by ZaxonXP** [insanum/gcalcli#757] opened 2024-09-16 09:41 UTC
Hi,

Once a year I add multiple events for a whole year with the following script:
```
#!/bin/bash

add_date() {
    local year=$1; shift
    local dates=("$@")

    for i in ${dates[*]}; do
        parts=(${i//,/ })
        gcalcli \
        --default-calendar Piotr \
        --calendar Piotr \
        --noincluderc \
        add \
        --details all \
        --reminder "1d email" \
        --reminder "1h email" \
        --reminder "15m email" \
        --title "Event" \
        --duration 180 \
        --noprompt \
        --when "$year.${parts[1]}.${parts[0]} 13:00"
    done
}
# day,month
dates1=( 31,08 14,09 28,09 12,10 19,10 09,11 23,11 07,12 14,12 )
dates2=( 11,01 25,01 15,02 08,03 22,03 12,04 10,05 24,05 14,06 28,06 05,07 )

add_date 2024 "${dates1[@]}"
add_date 2025 "${dates2[@]}"
```
After the upgrade of the `gcalcli` I noticed that this script no longer works in the automated way. The reason is that `gcalcli` now shows the calendar selection like this for each event I try to add:
```
0 Szkoła
1 Piotr
2 Family
Specify calendar from above:
```
Even the `--default-calendar` and `--calendar` options are used the `add` command still will not allow an automated entry (it goes into interactive). 

Can you please let me know if in the current version (`gcalcli v4.4.0`) it is possible to add events in the automatic mode?
If not, then can you please fix this?

Kind regards,
Piotr

**Comment by ZaxonXP** [comment] 2024-09-16 09:51
I found a workaround for the first question (how to make it work for now). Simply `echo 1 | gcalcli ...` will select the proper calendar. However this might backfire later on when the order of displayed calendars will be different in the future.
So, best would be to fix this issue.

**Comment by dbarnett** [comment] 2024-09-16 13:10
Looks like same symptom as #408, right? (But supposedly fixed there?)

IIUC in terms of expected/actual behavior, it wouldn't be strange for it to prompt you to choose calendar if you'd given multiple `--calendar`s (or just fail with error?), but here there's effectively only one calendar given… Could you see if dropping the `--default-calendar` helps as a workaround?

**Comment by ZaxonXP** [comment] 2024-09-16 13:31
I tried few different combinations with/without `default-calendar` and none of them worked. If I try as you suggeted:
```
gcalcli \
--noincluderc \
--calendar Piotr \
add \
--details all \
--reminder "1d email" \
--reminder "1h email" \
--reminder "15m email" \
--title "Event" \
--duration 180 \
--noprompt \
--when "2024.09.17 13:00"
```
then I still gets the prompt to select the calendar. 

The only way to make it work is NOT to specify the other calendars in the `.gcalclirc` file. This shows that the `--noincluderc` has no effect (unless there is some other undocumented purpose for this flag).

**Comment by ZaxonXP** [comment] 2024-09-16 13:46
I saw there is following description in the gcalcli help:
```
         --noincluderc         Whether to include ~/.gcalclirc when using
                               configFolder (default: True)
         --config-folder CONFIG_FOLDER
                               Optional directory to load/store all configuration
                               information (default: None)
```
So for me it looks like the `noincluderc` option should be used only when `config-folder` is in use. Right?

Having some other tries I figured out that it only works when the `gcalclirc` contains one `calendar` option. So having other `config-folder` where the `gcalclirc` file has only one calendar it works.
```
gcalcli \
--config-folder ~/.config/gcalcli/piotr \
--calendar Piotr \
add \
--details all \
--reminder "1d email" \
--reminder "1h email" \
--reminder "15m email" \
--title "Event" \
--duration 180 \
--noprompt \
--when "2024.09.17 13:00"
gcalcli \
--config-folder ~/.config/gcalcli/piotr \
--calendar Piotr \
add \
--details all \
--reminder "1d email" \
--reminder "1h email" \
--reminder "15m email" \
--title "Event" \
--duration 180 \
--noprompt \
--when "2024.09.17 13:00"
gcalcli \
--config-folder ~/.config/gcalcli/piotr \
--calendar Piotr \
add \
--details all \
--reminder "1d email" \
--reminder "1h email" \
--reminder "15m email" \
--title "Event" \
--duration 180 \
--noprompt \
--when "2024.09.17 13:00"
```
Looks like I will need to use two different config directories for different purposes.

**Comment by dbarnett** [comment] 2024-09-16 14:10
> Looks like I will need to use two different config directories for different purposes.

As a workaround for now, apparently, but let's get that fixed. =)

First thing, I think I'll change --noincluderc to work independently of --config-folder. I personally don't like the gcalclirc mechanism OR the --config-folder option, so I want to make --noincluderc nice and straightforward to use even if it's going to annoy a few users to change behavior in-place.

Second, can I clarify some expected behavior with you wrt some new config mechanisms I'm working on? I think the main reason for globally configuring a set of `--calendar`s is to hide spammy ones, and I've just implemented support for configuring a set of `calendars.ignore-calendars` for that purpose (see [README.md#configuration](https://github.com/insanum/gcalcli?tab=readme-ov-file#configuration)). Would those mechanisms cover your needs, without an additional layer of global `--calendar`s?

**Comment by ZaxonXP** [comment] 2024-09-16 14:45
The way I understood the `--calendar` option is that when specifies, the actions should be done on that calendar, even if the config file has more calendars defined. So when specifying `--nonincluderc` the other calendars should be disregarded. 

However. What about other options? Should they also be disregarded? Currently the config file also contains `client-id` and `client-secret`, which might be not a good idea to exclude from the settings when the `--nonincluderc` option is in use. I would advise maybe to store these auth related options in a separate file like `auth_config` or in a different section of the config file? That way using `--nonincluderc` option would drop all the `gcalclirc` options, but still using auth data.

Also, if I can suggest, it would be nice if `gcalcli` could check for the $XDG_CONFIG_HOME/gcalcli presence and (if found) use this as default config dir location. That way we can keep a home folder better organized. Or the GCALCLI_CONFIG option is also fine.

Yur idea with the ignore calendard is good. I have few calendars which (by default) I have hidden, so that would also work. But together with this config options, when `--calendar <name>` option is used from the command line, I would expect that the only specified calendar(s) are used to display/modification.

I hope this helps. :)

Kind regards,
Piotr

**Comment by dbarnett** [comment] 2024-09-16 15:20
Thanks, yep that's all good info and pretty aligned with the pieces already in progress. Sounds like you agree then that there's no reason there needs to be a global `--calendar` arg not linked to particular commands (besides backwards compatibility)?

Here the precedence gets all funny because the code literally can't distinguish between `--calendar` in gcalclirc and explicit `--calendar` on your cli. That's one of the ways gcalclirc is a footgun. But if it were generally reserved to be passed to individual commands, `add --calendar=Piotr` would mean `add --calendar=Piotr`, regardless of any other configs.

The other stuff is already shaping up nicely, stay tuned for 4.5 release :sunglasses: ...

> Currently the config file also contains client-id and client-secret, which might be not a good idea to exclude from the settings when the --nonincluderc option is in use.

Yup, #755 :heavy_check_mark: (and --noincluderc would still apply _ONLY_ to gcalclirc, any override we may end up adding to exclude config.toml would be independent)

> it would be nice if gcalcli could check for the $XDG_CONFIG_HOME/gcalcli presence and (if found) use this as default config dir location

#740 :heavy_check_mark:

**Comment by dbarnett** [comment] 2024-09-17 04:20
K, #758 fixed remaining loose ends here:

1. --noincluderc will actually do its job to keep those --calendar lines from leaking into your invocation
2. if you do still end up with multiple --calendars specified, you'll get a clear warning explaining what's going on (and even suggesting to try adding --noincluderc)
3. going forward, you can move the --calendar args after the command and get more robust handling (for example, in the case of `add`, it knows --calendar is singular and gives the final --calendar value precedence over any previous calendar values instead of trying to use multiple and getting confused)

Later I'll probably clean it up to use a predictable sort order when it does end up outputting a list of options, but these changes I landed already should be plenty to avoid confusion like you ran into.

**Closed by dbarnett** 2024-09-17 04:20 UTC
Labels: config

**Comment by ZaxonXP** [comment] 2024-09-19 12:28
If I might add something to this topic.

I think `mpv` has nice config structure. It has general, which apply to all and the `profiles` where you can have an extra options or overwrite the global settings.

I think this would be nice to have in `gcalcli`.
