### ISSUE TITLE
OAuth Client ID token_expiry in 7 days

### ISSUE THREAD

**Issue by NuvolaF** [insanum/gcalcli#809] opened 2024-10-18 17:07 UTC
Hi, I have a problem with creating the OAuth Client ID.
Every time I create it, it expires after 7 days and then the program stops working.
I read that to solve it, you have to set the "Publishing status" to "In production" but as soon as I try to log in with a new "OAuth Client ID" I get the error message "Access blocked: gcalcli app request is invalid - Error 400: invalid_request".
If I set the Publishing status to "Testing" everything starts working again for another 7 days.
Is there a way to authenticate gcalcli with a longer expiration?
Thanks a lot for the support.
Filippo

**Comment by dbarnett** [comment] 2024-10-19 20:57
Dupe of #628. Please follow up there.

**Closed by dbarnett** 2024-10-19 20:57 UTC
