### ISSUE TITLE
Cannot trigger auth flow

### ISSUE THREAD

**Issue by benhartley** [insanum/gcalcli#185] opened 2015-03-20 23:57 UTC
I have just installed using `sudo pip install gcalcli` on OS X 10.10.2 (Python 2.7.6). When I try and call an intial function in order to trigger the auth flow, I get the following output:

```
WARNING:root:This function, oauth2client.tools.run(), and the use of the gflags library are deprecated and will be removed in a future version of the library.
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2457, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2296, in BowChickaWowWow
    client_secret=FLAGS.client_secret
  File "/usr/local/bin/gcalcli", line 582, in __init__
    self._GetCached()
  File "/usr/local/bin/gcalcli", line 691, in _GetCached
    calList = self._CalService().calendarList().list().execute()
  File "/usr/local/bin/gcalcli", line 648, in _CalService
    http=self._GoogleAuth())
  File "/usr/local/bin/gcalcli", line 637, in _GoogleAuth
    storage)
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/oauth2client/old_run.py", line 120, in run
    authorize_url = flow.step1_get_authorize_url()
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 1827, in step1_get_authorize_url
    return _update_query_params(self.auth_uri, query_params)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 435, in _update_query_params
    parts = urllib.parse.urlparse(uri)
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlparse'
```

Output of `pip list`:

```
altgraph (0.10.2)
bdist-mpkg (0.5.0)
bonjour-py (0.3)
dateutils (0.6.6)
gcalcli (3.2)
google-api-python-client (1.4.0)
httplib2 (0.9)
macholib (1.5.1)
matplotlib (1.3.1)
modulegraph (0.10.4)
numpy (1.8.0rc1)
oauth2client (1.4.7)
pip (6.0.8)
py2app (0.7.3)
pyasn1 (0.1.7)
pyasn1-modules (0.0.5)
pyobjc-core (2.5.1)
pyobjc-framework-Accounts (2.5.1)
pyobjc-framework-AddressBook (2.5.1)
pyobjc-framework-AppleScriptKit (2.5.1)
pyobjc-framework-AppleScriptObjC (2.5.1)
pyobjc-framework-Automator (2.5.1)
pyobjc-framework-CFNetwork (2.5.1)
pyobjc-framework-Cocoa (2.5.1)
pyobjc-framework-Collaboration (2.5.1)
pyobjc-framework-CoreData (2.5.1)
pyobjc-framework-CoreLocation (2.5.1)
pyobjc-framework-CoreText (2.5.1)
pyobjc-framework-DictionaryServices (2.5.1)
pyobjc-framework-EventKit (2.5.1)
pyobjc-framework-ExceptionHandling (2.5.1)
pyobjc-framework-FSEvents (2.5.1)
pyobjc-framework-InputMethodKit (2.5.1)
pyobjc-framework-InstallerPlugins (2.5.1)
pyobjc-framework-InstantMessage (2.5.1)
pyobjc-framework-LatentSemanticMapping (2.5.1)
pyobjc-framework-LaunchServices (2.5.1)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (2.5.1)
pyobjc-framework-PubSub (2.5.1)
pyobjc-framework-QTKit (2.5.1)
pyobjc-framework-Quartz (2.5.1)
pyobjc-framework-ScreenSaver (2.5.1)
pyobjc-framework-ScriptingBridge (2.5.1)
pyobjc-framework-SearchKit (2.5.1)
pyobjc-framework-ServiceManagement (2.5.1)
pyobjc-framework-Social (2.5.1)
pyobjc-framework-SyncServices (2.5.1)
pyobjc-framework-SystemConfiguration (2.5.1)
pyobjc-framework-WebKit (2.5.1)
pyOpenSSL (0.13.1)
pyparsing (2.0.1)
pyrtm (0.4.2)
python-dateutil (1.5)
python-gflags (2.0)
pytz (2013.7)
rsa (3.1.4)
scipy (0.13.0b1)
setuptools (1.1.6)
simplejson (3.6.5)
six (1.9.0)
Twisted (13.2.0)
uritemplate (0.6)
xattr (0.6.4)
zope.interface (4.1.1)
```

**Comment by tresni** [comment] 2015-03-23 08:24
I can't reproduce this..  Can you try reinstalling six?

`pip install -U --force-reinstall six`

Also, are you passing anything to `gcalcli` when you invoke it?  (For reference, I'm testing on OSX 10.10.2, Python 2.7.9, Homebrew.  Few modules different, but nothing that looks related.

```
pyOpenSSL (0.14)
python-dateutil (2.4.1)
pytz (2015.2)
setuptools (12.0.5)
```
)

**Comment by benhartley** [comment] 2015-03-24 14:14
I just tried reinstalling `six` but getting the same error. I'm invoking with `gcalcli list` and others return same error (e.g. `gcalcli calm`)

**Comment by tresni** [comment] 2015-03-24 16:12
Are you using Homebrew, MacPorts or just the native Python installed on OSX?

**Comment by benhartley** [comment] 2015-03-26 12:52
I'm using the native bundled Python

**Comment by tresni** [comment] 2015-03-28 22:42
I can't reproduce this on 10.10.2 with Python 2.7.6:

```
 » /usr/bin/python --version
Python 2.7.6

 » /usr/bin/python /usr/local/bin/gcalcli list
WARNING:root:This function, oauth2client.tools.run(), and the use of the gflags library are deprecated and will be removed in a future version of the library.
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Furlshortener&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=232867676714.apps.googleusercontent.com&access_type=offline

If your browser is on a different machine then exit and re-run
this application with the command-line parameter

  --noauth_local_webserver

Authentication successful.
 Access  Title
 ------  -----
  owner  Family
  owner  Birthdays
  owner  Brian Hartvigsen
 reader  Birthdays

 » /usr/bin/python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
```

Couldn't install `pip` as it tried to overwrite homebrew... *sigh* so I just did `sudo /usr/bin/easy_install python-gflags google-api-python-client` to get the required dependancies.  From what I can tell from the logs I have:

* python-gflags 2.0
* google-api-python-client 1.4.0
* uritemplate 0.6
* six 1.9.0
* oauth2client 1.4.7
* httplib2 0.9
* simplejson 3.6.5
* rsa 3.1.4
* pyasn1-modules 0.0.5
* pyasn1 0.1.7

At this point I've got nothing...

**Comment by benhartley** [comment] 2015-03-28 23:06
OK thanks, I appreciate the effort to reproduce. Feel free to close the issue.

**Comment by tresni** [comment] 2015-03-29 17:36
Closing pending someone else who can reproduce.

**Closed by tresni** 2015-03-29 17:36 UTC

**Comment by mguina** [comment] 2015-04-09 18:31
I'm getting this same issue

Installed via `sudo pip install gcalcli`

Running for the first time, never authorised and when calling `gcalcli list` (or any other command) I get the following;

```
WARNING:root:This function, oauth2client.tools.run(), and the use of the gflags library are deprecated and will be removed in a future version of the library.
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2457, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2296, in BowChickaWowWow
    client_secret=FLAGS.client_secret
  File "/usr/local/bin/gcalcli", line 582, in __init__
    self._GetCached()
  File "/usr/local/bin/gcalcli", line 691, in _GetCached
    calList = self._CalService().calendarList().list().execute()
  File "/usr/local/bin/gcalcli", line 648, in _CalService
    http=self._GoogleAuth())
  File "/usr/local/bin/gcalcli", line 637, in _GoogleAuth
    storage)
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/oauth2client/old_run.py", line 120, in run
    authorize_url = flow.step1_get_authorize_url()
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 1827, in step1_get_authorize_url
    return _update_query_params(self.auth_uri, query_params)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 435, in _update_query_params
    parts = urllib.parse.urlparse(uri)
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlparse'
```
result of `pip list`
```
altgraph (0.10.2)
bdist-mpkg (0.5.0)
bonjour-py (0.3)
Cheetah (2.4.4)
dateutils (0.6.6)
gcalcli (3.2)
google-api-python-client (1.4.0)
httplib2 (0.9)
macholib (1.5.1)
Markdown (2.5.1)
matplotlib (1.3.1)
modulegraph (0.10.4)
numpy (1.8.0rc1)
oauth2client (1.4.7)
parsedatetime (1.4)
pip (6.1.1)
py2app (0.7.3)
pyasn1 (0.1.7)
pyasn1-modules (0.0.5)
pyobjc-core (2.5.1)
pyobjc-framework-Accounts (2.5.1)
pyobjc-framework-AddressBook (2.5.1)
pyobjc-framework-AppleScriptKit (2.5.1)
pyobjc-framework-AppleScriptObjC (2.5.1)
pyobjc-framework-Automator (2.5.1)
pyobjc-framework-CFNetwork (2.5.1)
pyobjc-framework-Cocoa (2.5.1)
pyobjc-framework-Collaboration (2.5.1)
pyobjc-framework-CoreData (2.5.1)
pyobjc-framework-CoreLocation (2.5.1)
pyobjc-framework-CoreText (2.5.1)
pyobjc-framework-DictionaryServices (2.5.1)
pyobjc-framework-EventKit (2.5.1)
pyobjc-framework-ExceptionHandling (2.5.1)
pyobjc-framework-FSEvents (2.5.1)
pyobjc-framework-InputMethodKit (2.5.1)
pyobjc-framework-InstallerPlugins (2.5.1)
pyobjc-framework-InstantMessage (2.5.1)
pyobjc-framework-LatentSemanticMapping (2.5.1)
pyobjc-framework-LaunchServices (2.5.1)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (2.5.1)
pyobjc-framework-PubSub (2.5.1)
pyobjc-framework-QTKit (2.5.1)
pyobjc-framework-Quartz (2.5.1)
pyobjc-framework-ScreenSaver (2.5.1)
pyobjc-framework-ScriptingBridge (2.5.1)
pyobjc-framework-SearchKit (2.5.1)
pyobjc-framework-ServiceManagement (2.5.1)
pyobjc-framework-Social (2.5.1)
pyobjc-framework-SyncServices (2.5.1)
pyobjc-framework-SystemConfiguration (2.5.1)
pyobjc-framework-WebKit (2.5.1)
pyOpenSSL (0.13.1)
pyparsing (2.0.1)
python-dateutil (2.4.2)
python-gflags (2.0)
pytz (2013.7)
rsa (3.1.4)
scipy (0.13.0b1)
setuptools (1.1.6)
simplejson (3.6.5)
six (1.9.0)
Twisted (13.2.0)
uritemplate (0.6)
vobject (0.6.6)
xattr (0.6.4)
zope.interface (4.1.1)
```
and as per the above suggestions I ran `pip install -U --force-reinstall six` which was successful, but made no difference.

OSX 10.10.3
Python 2.7.6

**Comment by nutritious** [comment] 2015-05-19 19:09
I had exactly the same issue. Removing 'everything' that `pip` installed:`sudo pip freeze | sudo xargs pip uninstall -y` and reinstalling `gcalcli` from sources fixed the problem.
```
>pip list
dateutils (0.6.6)
gcalcli (3.2)
google-api-python-client (1.4.0)
httplib2 (0.9.1)
oauth2client (1.4.10)
pip (6.1.1)
pyasn1 (0.1.7)
pyasn1-modules (0.0.5)
python-dateutil (2.4.2)
python-gflags (2.0)
pytz (2015.4)
rsa (3.1.4)
setuptools (1.1.6)
simplejson (3.7.1)
six (1.9.0)
uritemplate (0.6)
```

**Comment by howdoicomputer** [comment] 2015-06-30 21:00
I got the same error on OS X 10.10.3. I tried uninstalling and reinstalling. I'm using HomeBrew installed Python 2.7.

**Comment by nkipreos** [comment] 2015-06-30 21:27
Hi, 
 I uninstalled gcalcli, reinstalled it from source, restarted the terminal and it worked like a charm.

**Comment by bitfield** [comment] 2015-07-04 17:40
Same problem here: OS X 10.10.4, built-in Python, `sudo easy_install pip`, `sudo pip install gcalcli`, `gcalcli agenda` =>

	WARNING:root:This function, oauth2client.tools.run(), and the use of the gflags library are deprecated and will be removed in a future version of the library.
	Traceback (most recent call last):
	  File "/usr/local/bin/gcalcli", line 2555, in <module>
	    BowChickaWowWow()
	  File "/usr/local/bin/gcalcli", line 2384, in BowChickaWowWow
	    allDay=FLAGS.allday
	  File "/usr/local/bin/gcalcli", line 603, in __init__
	    self._GetCached()
	  File "/usr/local/bin/gcalcli", line 728, in _GetCached
	    self._CalService().calendarList().list())
	  File "/usr/local/bin/gcalcli", line 684, in _CalService
	    http=self._GoogleAuth())
	  File "/usr/local/bin/gcalcli", line 673, in _GoogleAuth
	    storage)
	  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
	    return wrapped(*args, **kwargs)
	  File "/Library/Python/2.7/site-packages/oauth2client/old_run.py", line 120, in run
	    authorize_url = flow.step1_get_authorize_url()
	  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
	    return wrapped(*args, **kwargs)
	  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 1873, in step1_get_authorize_url
	    return _update_query_params(self.auth_uri, query_params)
	  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 442, in _update_query_params
	    parts = urllib.parse.urlparse(uri)
	AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlparse'

**Comment by benhartley** [comment] 2015-07-06 09:24
Feels like a PR with a note in the docs would make this go away?
