### ISSUE TITLE
ImportError: No module named oauth2client1412.client

### ISSUE THREAD

**Issue by killown** [insanum/gcalcli#299] opened 2017-05-20 21:35 UTC
➜  ~ gcalcli agenda         
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 2647, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 2497, in BowChickaWowWow
    gcal.AgendaQuery()
  File "/usr/bin/gcalcli", line 1730, in AgendaQuery
    eventList = self._SearchForCalEvents(start, end, None)
  File "/usr/bin/gcalcli", line 1629, in _SearchForCalEvents
    work = self._CalService().events().\
  File "/usr/bin/gcalcli", line 694, in _CalService
    http=self._GoogleAuth())
  File "/usr/bin/gcalcli", line 673, in _GoogleAuth
    credentials = storage.get()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 407, in get
    return self.locked_get()
  File "/usr/lib/python2.7/site-packages/oauth2client/file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 309, in new_from_json
    module_obj = __import__(module_name)
ImportError: No module named oauth2client1412.client

➜ pacman -Ss oauth2client
community/python-oauth2client 4.0.0-3 [installed]
    A client library for OAuth 2.0
community/python2-oauth2client 4.0.0-3 [installed]
    A client library for OAuth 2.0

**Comment by duckunix** [comment] 2017-10-09 18:23
Also seen on Ubuntu 17.10:

> dpkg -l | grep oauth2                                
> ii  python-oauth2client         3.0.0-1        all          OAuth 2.0 client library - Python 2.7
> ii  python3-oauth2client       3.0.0-1        all          OAuth 2.0 client library - Python 3.x

**Comment by tresni** [comment] 2017-10-10 19:29
What version of gcalcli?  If it's anything pre-4.0.0a1 then you need to make sure oauth2client isn't upgraded past 1.4.12.

**Comment by tresni** [comment] 2017-10-10 19:31
I believe this is a duplicate of #293

**Closed by tresni** 2017-10-10 19:31 UTC
