### ISSUE TITLE
Out-Of-Band (OOB) flow

### ISSUE THREAD

**Issue by denis734552** [insanum/gcalcli#684] opened 2024-07-03 22:52 UTC
I was running gcalcli from container and had to authenitcate it every week with '--noauth_local_webserver' option.  Like having this:

```
Go to the following link in your browser:

    `https://accounts.google.com/o/oauth2/v2/auth?client_id=XXXXXXXXXXXXXXX.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%....se_type=code`


Enter verification code:
```
then copying link to external browser, getting verification code and copying it back to the container. As I understand correctly it is caled OOB (out-Of-Band) method.
Starting recently , it started to show me error 404 saying in the details that OOB is no longer supported by Google 
[started from 01.31.20023](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration).

Is it possible to use different options than OAuth2.0 for authentication in the environments, when web browser is not available?
Liike:
1. API key   (not sure if this is the right option, but mentioned it anyway)
2. OAuth 2.0 Device Flow (this flow is designed specifically for applications without a web browser)

**Comment by dbarnett** [comment] 2024-08-23 16:54
Dupe of #626. Let's continue discussion there.

**Closed by dbarnett** 2024-08-23 16:54 UTC
