### ISSUE TITLE
Authentication hanging

### ISSUE THREAD

**Issue by maddn** [insanum/gcalcli#66] opened 2013-02-25 12:08 UTC
Hi,

I updated to the latest gcalcli version. Now I have to log into my google account in the browser, and select Allow access. But then the browser hangs indefinitely saying Waiting for localhost...

I've tried using different browsers, and I've tried googling for a solution, but I'm totally stuck. I'm sure I'm missing something obvious.

Thanks,
Michael

**Comment by jcrowgey** [comment] 2018-07-11 02:42
I tried to reproduce this with the current release on debian.  I tried with my default browser (firefox) and with ${BROWSER} set to chromium, both behaved as expected.  Since it's been over 5 years since this issue has been updated, I'm closing it under the assumption that it's fixed.

**Closed by jcrowgey** 2018-07-11 02:42 UTC
