### ISSUE TITLE
ical import failure

### ISSUE THREAD

**Issue by githubgnulinux** [insanum/gcalcli#323] opened 2017-10-26 12:41 UTC
command: gcalcli import file.ics --calendar mycalendar@...

Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2647, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2634, in BowChickaWowWow
    gcal.ImportICS(FLAGS.verbose, FLAGS.dump, FLAGS.reminder, args[1])
  File "/usr/local/bin/gcalcli", line 2118, in ImportICS
    body=event))
  File "/usr/local/bin/gcalcli", line 654, in _RetryWithBackoff
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)

**Comment by tresni** [comment] 2017-10-27 19:47
Can you paste the full output of the failure?  The actually error message isn't shown here.  Additionally an ics that fails would be helpful.

**Comment by githubgnulinux** [comment] 2017-11-04 15:21
Full output was as shown. The ics file cannot be posted; privacy.

**Comment by tresni** [comment] 2017-11-04 15:48
Unfortunately I'm not going to be able to do anything with this then.  I can't reproduce it and there's not enough information to reproduce.

**Comment by jcrowgey** [comment] 2018-08-25 16:47
I'm closing this since we can't repro.

@githubgnulinux your privacy concerns are certainly valid.  If there's some way that you can redact the private information in the file and still reproduce the bug then we'd like to reopen this.

**Closed by jcrowgey** 2018-08-25 16:47 UTC
